### ISSUE TITLE
Year dropdown displays wrong year

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#1003]
On the member side, homepage, there's a activity history with a dropdown.
When selecting a year in the dropdown, the correct activities are loaded, but the current year is always displayed.
Instead, the year that is selected should be displayed.

**Comment by Raymonzut** [comment]
@Riscky could this be a duplicate of #833?

**Comment by Riscky** [comment]
Yes, that's correct.
Thanks for pointing this out!
