### ISSUE TITLE
/Apps/Products searchbar for products

### ISSUE THREAD

**Issue by GitBreax** [svsticky/constipated-koala#1024]
Small feature request for adding a searchbar in the products page so it is easier. 
Due to high number of added products having to use ctrl+f is cumbersome.

**Comment by JustNireon** [comment]
We will hopefully soon migrate to https://github.com/svsticky/undead-mongoose, so it's probably not worth fixing

**Comment by Mstiekema** [comment]
Moved to Moved to https://github.com/svsticky/undead-mongoose/issues/29
