### ISSUE TITLE
/Apps/Products archive button

### ISSUE THREAD

**Issue by GitBreax** [svsticky/constipated-koala#1025]
Some added products were one-of and do not need to show in the list of products. Being able to archive these would help improve the visual clutter of the current page.

**Comment by JustNireon** [comment]
We will hopefully soon migrate to https://github.com/svsticky/undead-mongoose, so it's probably not worth fixing

**Comment by Mstiekema** [comment]
Moved to https://github.com/svsticky/undead-mongoose/issues/29
