### ISSUE TITLE
Enroll random button

### ISSUE THREAD

**Issue by Siem2l** [svsticky/constipated-koala#1038]
Just a shitty dice button top right of reservist to enroll a random reservist instead of most recent reservist. Some activities enrollment are currently being capped by the server capacity and shouldn't be seen as fair(internet connection, luck of nginx letting your request pass.  etc). With this button users would enroll to the reservist pool first and after the initial enrollment, board could use this button to randomly enroll participants.

I'm sure there are fancier ways to do this, but this is probably the easiest and fastest solution for now.

**Comment by SilasPeters** [comment]
@PrinceMordred @SanderHageman , is this issue in-line with the new board plans?
