### ISSUE TITLE
Addition of the MSc Data Science

### ISSUE THREAD

**Issue by SpookyBoy99** [svsticky/constipated-koala#1057]
### Expected behaviour

MSc Data Science is present in the dropdown list of available studies both on the enrolment page and in the user edit page

### Actual behavior

MSc Data Science is missing from the list of available studies.

### Steps to reproduce
- admin/user
- browser: Firefox

**Comment by SilasPeters** [comment]
Thanks for helping out! We will have a look at both of your issues soon

**Comment by TobiasDeBruijn** [comment]
@Mstiekema If I understand correctly, I need to modify the `seeds.rb` file to add the study, and then execute an INSERT query on prod as well to add the study there too, right?

@SpookyBoy99 What is the code for Msc Data Science?

**Comment by SilasPeters** [comment]
I believe a whole button is missing as a whole. I understand this issue as 'Adding a Data Sciences study is not possible'.

But yes, the seeding needs to be adjusted regardless of this misunderstanding.

**Comment by TobiasDeBruijn** [comment]
>I believe a whole button is missing as a whole. I understand this issue as 'Adding a Data Sciences study is not possible'.
I don't think there even is a button, needs to be added with a query as far as I know.

**Comment by SilasPeters** [comment]
So we are not talking about the dropdown list presented when you - as a member - have to enter your current study?

**Comment by TobiasDeBruijn** [comment]
We are :) There's just no button in the Admin UI to add the study, it's a change that needs to be made as a postgres query.

I think I know how to add it, but I do want Merijn or Sander to confirm my change would be correct.

**Comment by SilasPeters** [comment]
@TobiasDeBruijn have you gotten that confirm yet? It would be nice if this would be fixed before the start of the year

**Comment by TobiasDeBruijn** [comment]
Have not unfortunately (@SanderHageman 🙏 )
