### ISSUE TITLE
Confidentiality contact person page

### ISSUE THREAD

**Issue by SilasPeters** [svsticky/constipated-koala#1077]
This page should provide all information for a student (not per say member) to contact the confidentiality people.

The page should not require the user to log in (or have a koala account), and the message should possibly be anonymous. It should also be protected with ReCaptcha or something.

User should be able to provide an optional email adress, or other contact information.

For the full idea, contact Mervin @SpookyBoy99 .

**Comment by SpookyBoy99** [comment]
This will not be a part of Constipated Koala, a separate project has been created at [svsticky/fallacious-rooster](https://github.com/svsticky/fallacious-rooster).
