### ISSUE TITLE
Refactoring views

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/constipated-koala#168]
### Search

Search in members, activities, and groups. Creating a new search result view, with rows and an icon infront with the type of the record. A google like search view!
### Logging

Filterable, better logging overall, more links to relevant objects
### iDeal

Make it filterable and better descriptions
- [x] ideal view
- [x] settings 
- [x] ideal
- [ ] search
- [ ] logging

**Comment by Riscky** [comment]
Closing this issue because it is stale, if parts of the issue are still relevant, please create separate issues
