### ISSUE TITLE
Changing group model and view to show history

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/constipated-koala#169]
### Expected behaviour

In the group view, the year to be viewed can be chosen, and then only groups which have a presence in that year will be shown. In that scenario a group can have a separate name per year, while the names of each year are saved for future reference.

Some way should be implemented to give the user the option to create either a new group or a new "edition" of an existing group. Groups should probably have a "parent name" in that case, and names per year.
### Actual behavior

In the group view, all groups are shown. Including groups which are not present this year. Also there is only one name possible for a group, while some groups (like freshmen committees) change their name every year. At the moment the comments field is used for this, but this is not that nice.

**Comment by Riscky** [comment]
Specific names per group can be added in the notes field, which is sufficient
