### ISSUE TITLE
Open-source

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/constipated-koala#181]
`Constipated-koala` is started with the idea of open-sourcing it. However along the way I decided to use Flatify (because it was hidious!) which is a styling under a license, hence we can not share the styling.

If ever someone would want to change the style it should be done by replacing [flatify.css](https://github.com/svsticky/constipated-koala/blob/development/vendor/assets/stylesheets/flatify.css), than we can open-source it and everyone can help or use the api.

Last few months I been realy working on documentation and I think for now it will suffice, if you want to you can run it. (nginx config might be to specific for sticky)

**Comment by Riscky** [comment]
For now, we will leave flatify in the repo. Although not completely legal, we think it is not worth the hassle now. A good time for recreating or purging the repo would be the summer holidays, when no active development is going on. I will make a new issue, referring to this one
