### ISSUE TITLE
Improve member interface

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/constipated-koala#189]
Following #144 the UI for members. In such that they can;
- [ ] edit their information and study information (since cs.uu.nl proves to be wrong sometimes),
- [ ] viewing rights to all committees and their members (names),
- [ ] viewing rights of all activities,
- [x] option to join upcoming activities (but not all, lidmaatschap, studytrip),
- [x] be able to cancel an activity participation (but not all, same as above),
- [x] be able to see who is participating in an activity,
- [ ] include information for incasso's or pay using ideal, and
- [x] activate checkout cards (as well as a link mailed to the member).

Joining activities is a large problem and in my opinion should be done after the earlier mentioned issues are done. The problem from joining activities is that members can subscribe whenever they want, including 5 minutes before the activity, and even more annoying cancel it before an activity. There are a few options to deal with this and I'm not sure which is best; 
- cancel before a certain time limit, two days before the activity or so, 
- one can cancel however if there is no replacement you still have to pay, or
- no cancelling at al, e-mail to a board member and request it.

All activities should have at least the option to disallow cancelling participating and to disallow joining, for example lidmaatschap and studytrip (where additional information is required and a secondary website is made <sup>1</sup>). 

The transition is kinda hard I guess since users cannot subscribe on the well-known lists anymore. 

<sup>1</sup> For example [joining an activity](https://github.com/svsticky/promo-skeleton/tree/feature/koala-oauth) as studytrip using oauth let's the user subscribe to an event using a dedicated website. The user in fact joins the activity however especially for a studytrip members have to be selected hence have to be removed from the list by an admin.

**Comment by Riscky** [comment]
Closing this issue because it is stale, if parts of this issue are still relevant, separate issues should be made
