### ISSUE TITLE
Improve authentication in the Checkout API

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/constipated-koala#201]
As mentioned in an [issue](../../checkout/issues/21) in Checkout, the current token-based authentication used in the Checkout API is suboptimal, in a security perspective.

A possible solution for this problem, the best one @svsticky/it-crowd could come up with while doing a short brainstorm, would be to overhaul the Checkout API, and get rid of the token altogether. 

Authentication would take place on a user level, and the transaction requests to the API should include a personal pin code, that the user would have set at sometime, and has to enter when doing any transaction. This basically means the Checkout app ends up with two-factor authentication on a user-by-user basis. The products would be requested by the app without any authentication, but this would probably not really be a problem.

There may be better solutions to this problem, so a discussion is welcome.

**Comment by Riscky** [comment]
The hardcoded token is a problem with checkout, I created an issue there
