### ISSUE TITLE
Zichtbaarheid openstaande betalingen vorig jaar

### ISSUE THREAD

**Issue by duijf** [svsticky/constipated-koala#213]
### Steps to reproduce
1. Log in als lid
2. Kijk naar openstaande betalingen
### Actual behavior

Systeem laat een totaal te betalen overzicht zien, maar niet de individuele activiteiten die nog open staan (van het vorig boekjaar)
### Expected behaviour

Systeem geeft overzicht van alle activiteiten waarvoor nog betaald moet worden, **en** het totaal.

Ik meen me te herinneren dat er een flink aantal bugs zijn vanwege het niet weergeven van informatie terwijl dit wel nodig is. Misschien handig om te kijken naar het standaard gedrag omtrent deze functionaliteit en dit te heroverwegen

**Comment by Mstiekema** [comment]
Er is al een dropdown voor het bekijken van activiteiten van vorige jaren.
