### ISSUE TITLE
Hardcoded strings in views and javascript

### ISSUE THREAD

**Issue by maartenberg** [svsticky/constipated-koala#222]
At the moment, the javascript assets and views contain several hardcoded strings (in dutch), which is unhelpful if we actually decide to fully support multiple languages. The main problem for translating javascript is that we then would have to get Rails' translations into the javascript somehow, either by preprocessing the files before serving them to the clients (eliminating the need for javascript code changes, but increasing load time), by making the [translations available in a property], which is less than ideal, or by requiring compiling the javascript (which makes it somewhat more complicated to run koala).

1. Do we want to do this, and
2. Which method would be the best?

[translations available in a property]: http://stackoverflow.com/a/10610347

**Comment by Mstiekema** [comment]
This has been fixed in #638
