### ISSUE TITLE
Oauth enrollment

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/constipated-koala#243]
Doordat er een nieuwe manier is van inschrijven moet de oauth api voor het inschrijven van activiteiten ook worden aangepast. Deze functionaliteit was bedoeld voor websites zoals die van de studiereis waar een lid kan inloggen en inschrijven voor de studiereis.

~~Of oauth moet verwijderd worden, wat ik wel jammer zou vinden~~

**Comment by Riscky** [comment]
The is currently no use case for this, closing the issue
