### ISSUE TITLE
iCal integration

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#291]
I know this has been said several times already, but today I found a possible way to implement the "add to calendar"-integration thanks to the recent redesign of Calendar. 

I found that it is possible to 'publish' a calendar events. Clicking the dialog gives us the option to copy the HTML code of a direct link. Copying the HTML code leaves us with the iconic 'add to calendar' button, specifically for that event. Abstracted for use on all events gives us:
`<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=EVENT_ID&amp;tmsrc=stickyutrecht.nl_thvhicj5ijouaacp1elsv1hceo%40group.calendar.google.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_nl.gif"></a>`

Where `EVENT_ID` is the ID of the event itself, also found in the link of the event-edit view in calendar. 

My idea for this implementation:
1. Create an dropdown-entry field in the activity-edit admin view which gets all the current events in Sticky's public calendar and displays these by name. The admin can select a event by name.
2. Add a row to the activity-view for users which displays the button with the HTML as displayed above.
3. When an admin has specified a calendar event in Sticky's public agenda in the activity edit admin view, the ID is inserted in the HTML and thus the "add to calendar" button is created. 

I now manually added the button to one of our activities as a prototype, you can view it here:
[https://koala.svsticky.nl/activities/494](https://koala.svsticky.nl/activities/494) (you need to be logged in as a user)

@HugoPeters1024 already has some experience with Calendar's API and might be able to help displaying the names of the events in the dropdown-list. 

Also, this way ensures an admin has added a event to the calendar because if not, he/she won't be able to select it from the dropdown ;)...

**Comment by Riscky** [comment]
This functionality is removed from Koala
