### ISSUE TITLE
Send greeting-mail also to by admin added members

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#293]
When an admin adds a member to Koala, this member should also receive the greeting-mail that new members get when signing up to Sticky via intro.svsticky.nl. This is especially useful for donators who are added by an admin to Koala.

**Comment by Mstiekema** [comment]
Has been fixed

**Comment by CrookedGrandma** [comment]
Ja verdomme @Mstiekema ik zit hier al een uur naar te kijken, is niks in gebeurd sinds januari, kom je nu hiermee jeez
