### ISSUE TITLE
Successfully activating a Checkout card as admin prints error

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/constipated-koala#306]
### Expected behaviour
Activating someone's Checkout card as admin prints a positive message and is logged.

### Actual behavior
It activates the card, but prints "kaart is niet geactiveerd" and does not log the action.

### Steps to reproduce
- admin/user: admin

Set a card's `active` attribute to `0` in the database. Then, as an admin, click the button in Koala to re-activate that Checkout card.

Tested in staging on 23113c5. Logs:
```
F, [2017-12-01T19:39:09.525871 #15497] FATAL -- : [943ccbb9-ba80-4986-b7b7-465e4af00935]
F, [2017-12-01T19:39:09.526700 #15497] FATAL -- : [943ccbb9-ba80-4986-b7b7-465e4af00935] NoMethodError (undefined method `impressions' for #<CheckoutCard:0x00564ff304fb98>
Did you mean?  impressionist_count):
F, [2017-12-01T19:39:09.526782 #15497] FATAL -- : [943ccbb9-ba80-4986-b7b7-465e4af00935]
F, [2017-12-01T19:39:09.527290 #15497] FATAL -- : [943ccbb9-ba80-4986-b7b7-465e4af00935] app/controllers/admin/checkout_products_controller.rb:96:in `activate_card'
```

**Comment by Riscky** [comment]
Issue is fixed in opensource release
