### ISSUE TITLE
Use Brakeman (static analysis security vulnerability checker) in CircleCI and fix found issues

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/constipated-koala#356]
I ran brakeman for the first time, it has given some vulnerabilities. These should be fixed, especially before #181 

== Brakeman Report ==

Application Path: /Users/martijn/Public/constipated-koala
Rails Version: 5.2.0
Brakeman Version: 4.3.1
Scan Date: 2018-07-13 07:27:41 +0200
Duration: 3.888607 seconds
Checks Run: BasicAuth, BasicAuthTimingAttack, ContentTag, CreateWith, CrossSiteScripting, DefaultRoutes, Deserialize, DetailedExceptions, DigestDoS, DynamicFinders, EscapeFunction, Evaluation, Execute, FileAccess, FileDisclosure, FilterSkipping, ForgerySetting, HeaderDoS, I18nXSS, JRubyXML, JSONEncoding, JSONParsing, LinkTo, LinkToHref, MailTo, MassAssignment, MimeTypeDoS, ModelAttrAccessible, ModelAttributes, ModelSerialize, NestedAttributes, NestedAttributesBypass, NumberToCurrency, PermitAttributes, QuoteTableName, Redirect, RegexDoS, Render, RenderDoS, RenderInline, ResponseSplitting, RouteDoS, SQL, SQLCVEs, SSLVerify, SafeBufferManipulation, SanitizeMethods, SelectTag, SelectVulnerability, Send, SendFile, SessionManipulation, SessionSettings, SimpleFormat, SingleQuotes, SkipBeforeFilter, StripTags, SymbolDoSCVE, TranslateBug, UnsafeReflection, ValidationRegex, WithoutProtection, XMLDoS, YAMLParsing

== Overview ==

Controllers: 26
Models: 19
Templates: 51
Errors: 1
Security Warnings: 10

== Warning Types ==

Cross-Site Scripting: 2
Format Validation: 2
Redirect: 5
SQL Injection: 1

== Errors ==

Error: /Users/martijn/Public/constipated-koala/app/controllers/api_controller.rb:10 :: parse error on value ["ensure", 10] (kENSURE)
Location: Could not parse /Users/martijn/Public/constipated-koala/app/controllers/api_controller.rb

== Warnings ==

Confidence: High
Category: Format Validation
Check: ValidationRegex
Message: Insufficient validation for 'phone_number' using /(^\+[0-9]{2}|^\+[0-9]{2}\(0\)|^\(\+[0-9]{2}\)\(0\)|^00[0-9]{2}|^0)([0-9]{9}$|[0-9\-\s]{10}$)/. Use \A and \z as anchors
File: app/models/member.rb
Line: 12

Confidence: High
Category: Format Validation
Check: ValidationRegex
Message: Insufficient validation for 'student_id' using /\F?\d{6,7}/. Use \A and \z as anchors
File: app/models/member.rb
Line: 18

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(IdealTransaction.new(:description => "Mongoose-tegoed", :amount => (ideal_transaction_params[:amount].to_f + Settings.mongoose_ideal_costs), :issuer => ideal_transaction_params[:bank], :member => Member.find(current_user.credentials_id), :transaction_id => nil, :transaction_type => "CheckoutTransaction", :redirect_uri => users_root_url).mollie_uri)
File: app/controllers/members/home_controller.rb
Line: 104

> the redirect is required since it is delivered from mollie, this cannot be fixed

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(IdealTransaction.find_by_uuid!(params[:uuid]).redirect_uri)
File: app/controllers/api/participants_controller.rb
Line: 30

> the redirect is required since it is delivered from mollie, this cannot be fixed

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(IdealTransaction.find_by_uuid!(params[:uuid]).redirect_uri)
File: app/controllers/api/participants_controller.rb
Line: 37

> the redirect is required since it is delivered from mollie, this cannot be fixed
> nice to check if all three redirects are still used

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(IdealTransaction.new(:description => ("Introductie #{Member.new(public_post_params.except(:participant_attributes)).name}"), :amount => (0 + Participant.create(:member => Member.new(public_post_params.except(:participant_attributes)), :activity => activity).currency), :issuer => params[:bank], :member => Member.new(public_post_params.except(:participant_attributes)), :transaction_id => Activity.find(public_post_params[:participant_attributes].to_h.select do  (participant["participate"].nil? or (participant["participate"].to_b == true))  end.map do  participant["id"].to_i  end).map(&:id), :transaction_type => "Activity", :redirect_uri => public_url).mollie_uri)
File: app/controllers/public_controller.rb
Line: 63

> the redirect is required since it is delivered from mollie, this cannot be fixed

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(IdealTransaction.find_by_token!(params[:token]).redirect_uri)
File: app/controllers/api/webhook_controller.rb
Line: 12

> the redirect is required since it is delivered from mollie, this cannot be fixed

Confidence: Medium
Category: SQL Injection
Check: SQL
Message: Possible SQL injection
Code: CheckoutBalance.where(:id => checkout_balance.id).limit(1).update_all("balance = balance + #{price}, updated_at = NOW()")
File: app/models/checkout_transaction.rb
Line: 24

> This should be done with interpolation; question mark as variable and pass as argument

Confidence: Weak
Category: Cross-Site Scripting
Check: CrossSiteScripting
Message: Unescaped model attribute
Code: current_user.credentials.signature
File: app/views/mailings/participants/inform.html.haml
Line: 18

Confidence: Weak
Category: Cross-Site Scripting
Check: CrossSiteScripting
Message: Unescaped model attribute
Code: current_user.credentials.signature
File: app/views/admin/settings/index.html.haml
Line: 113

**Comment by Riscky** [comment]
Brakeman still shows a bunch of warnings, we should defs check this in CircleCI and fix as much as possible
