### ISSUE TITLE
Enforce review of pull request on development-branch

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#366]
I saw @martijncasteel almost shouting several times to create pull requests for easier review of and commenting on commits fixing bugs, adding new features etc. I, too, think contributing through pull requests seems the better way. To ensure people will use pull-requests more often to show what they have been working on, I can protect the `development`-branch with the following settings, that also enforce at least one person to have reviewed the pull request: 
![screenshot_20180916_201358](https://user-images.githubusercontent.com/15898259/45599561-f5fa2800-b9ed-11e8-938a-1fc8b31feba9.png)

Let me know if any of you @svsticky/commit has something against this approach, otherwise I will enable this protection soon :).

**Comment by Riscky** [comment]
discussion is stale
