### ISSUE TITLE
"Abonneer!"-Button not working as intended

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#367]
### Expected behaviour
When a user clicks on the green "Abonneer!"-button, the user is able to add the Sticky activity-calendar to his/her calendar via his/her default calendar application.

### Actual behavior
When the button is clicked on a smartphone, nothing happens. If a user clicks on the button on a pc, the link is opened but doesn't open the default calendar application and errors.

### Steps to reproduce
- ~~admin~~/user
- browser: Chrome Desktop Version 70.0.3538.9 (Official Build) dev (64-bit) on Kubuntu 18.04, Chrome Mobile 70.0.3538.15 on Android 8.0

**Comment by Riscky** [comment]
Calendar integration was removed from Koala
