### ISSUE TITLE
Wrong timezone on calendar

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#368]
### Expected behaviour
When calendar is added to user's calendar application, it should show activities on the time they actually happen.

### Actual behavior
Entries in the calendar appear two hours later than they actually are.

### Steps to reproduce
- ~~admin~~/user
- browser: Chrome
1. Login as user
2. Add calendar (in some magical way, also see #367 :smile: )
3. Compare calendar dates with dates in koala-activities

**Comment by Riscky** [comment]
Calendar integration was removed from Koala
