### ISSUE TITLE
Gebruik modal voor 'Abonneer!'-knop

### ISSUE THREAD

**Issue by maartenberg** [svsticky/constipated-koala#374]
De error-view die is hergebruikt is niet heel erg responsive en we hebben al een ding om popups te showen dus het zou een optie kunnen zijn om een popup met een 'kopieer deze link' te geven als je op die knop drukt in plaats van het net (wel marginaal) verbeterde gedrag.

#itcrowdgang2018

**Comment by Riscky** [comment]
We don't have this button anymore
