### ISSUE TITLE
Webhooks?

### ISSUE THREAD

**Issue by maartenberg** [svsticky/constipated-koala#386]
I've half-seriously talked about this in the meetings before, but I seriously think that adding outgoing webhooks for some events in Koala could be a good idea to allow providing functionality without adding service-specific API links to Koala. Some examples:

- If a member's email changes, the email would be (ideally) also updated in the Mailchimp lists, or a board member should get an email with the previous and new address, to get a reminder that the email address needs to be updated.
- If an activity is created or changed, a signal could be sent to Google Calendar to create or update a matching activity.

If we had webhooks, this could then be done without coupling Koala itself to an external service we might stop using, and we could instead write some separate script that translates Koala's data to the API of whatever service that needs to be updated.

This is probably a big idea etc., so yeah. Thoughts?

**Comment by Riscky** [comment]
> usecase for webhook is unclear

We found a usecase for undead mongoose :)

**Comment by Riscky** [comment]
Closed by #921
