### ISSUE TITLE
Add section to member's edit user view with regard to his/her rights and how to enforce them (right to be forgotten)

### ISSUE THREAD

**Issue by emielvanrijn1** [svsticky/constipated-koala#390]
To make it easy for members to view and possible make use of their rights as stated in the GDPR, do we want to make a section to the member's user view? Pro: it is easy for a member to see his/her rights and what steps to take. Con: it is easy for a member to see his/her rights and what steps to take, maybe resulting in more requests...?

**Comment by FInnvos123** [comment]
Included in #470
