### ISSUE TITLE
Activity enrollment is based on the text of the button

### ISSUE THREAD

**Issue by maartenberg** [svsticky/constipated-koala#391]
At the current meeting, I was requested to look into exposing the English translation to members somehow. I found that this works well enough, but ran into an issue while testing the various functions that prevented me from enrolling to an activity.

The issue ended up being caused by the fact that the Javascript looks at the content of the enrollment button (`if button.text == "Inschrijven"`) to determine whether or not an activity is enrollable. This does not seem like an optimal solution to me, but I don't care enough to fix it right now. This blocks exposing the translation to members, but seems to be the only issue.

Relates to #222. 
Patch to enable locale selection based on subdomain is [here](https://gist.github.com/maartenberg/47c3fafe8443ccbaa0dc44276bb67017).

**Comment by Mstiekema** [comment]
It no longer blocks translations, since the string is compared to the translated value of the given string. It would still be nice if the behavior was changed
