### ISSUE TITLE
Is freshman wrongly designed

### ISSUE THREAD

**Issue by Ckef** [svsticky/constipated-koala#418]
### Expected behaviour

The "Is freshman" checkbox of an activity should make it so only freshman can enroll for that activity. A member is considered a freshman when it's his or her first year studying a bachelor. When someone transitions from one study to another after studying for a year, e.g. from GMT to INCA, and it's his or her first year of INCA, this person is not considered a freshman again, and he or she cannot enroll for a freshman activity anymore.

### Actual behavior

When someone transitions from one study to another, e.g. from GMT to INCA, this person is considered a freshman again as it's the first year of the INCA bachelor. The previous year studying GMT is not considered.

**Comment by Riscky** [comment]
Problems with freshmen activities still persist, it's definitely worth looking into this issue.
As far as I'm concerned a freshmen should be defined as: the start date of your first bachelor study registered at Sticky is no longer then 1 year ago.
