### ISSUE TITLE
Activity enrollable even if not shown in Koala

### ISSUE THREAD

**Issue by Ckef** [svsticky/constipated-koala#455]
As of now, when creating a new activity, `Inschrijfbaar` is disabled if `Toon in Koala` is false. But we would like to set the `Deelnemerslimiet` before making an activity public, this lowers human errors by board members.

We would like `Inschrijfbaar` to be enabled even if `Toon in Koala` is false. However ofcourse you cannot enroll an activity that is not shown in Koala.

**Comment by Riscky** [comment]
I don't think 'inschrijfbaar' should be enabled, just that the participation limit should not be disabled. This should be easy
