### ISSUE TITLE
Make Koala multilingual

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#486]
# Things that need to be done:
- [x] Update all missing translations (related: #396, #327)
- [x] Make a language choice thingy (flag in the edge of the page)
- [x] Make activity descriptions bilingual (optional) (tabs?)
- [x] Display all pages and content in the chosen language
- [x] Save user language preference

**Comment by Riscky** [comment]
related: #222

**Comment by Mstiekema** [comment]
This has been done in #647
