### ISSUE TITLE
Let outgoing mail comply to spam filter standards

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#495]
### Expected behaviour
Mail sent by a board member arrives in the inbox of participants.

### Actual behavior
Mail is often (especially in Outlook.com) found in the spam folder

**Comment by maartenberg** [comment]
This is not Koala's problem, but a problem with Mailgun. We can look into getting Mailgun to behave better / offend Outlook less, but we probably don't need code changes in Koala for that.

**Comment by martijncasteel** [comment]
We use a shared mailgun server, asking them to move our endpoint might help. You should in a ticket in the mailgun system

**Comment by Riscky** [comment]
Thanks for the feedback!
