### ISSUE TITLE
Contact gegevens van leden zichtbaar maken

### ISSUE THREAD

**Issue by michielvh1995** [svsticky/constipated-koala#510]
### Expected behaviour
Het zou handig zijn als Sticky een online ledenlijst krijgt, die je als lid in kan zien, met daarin contact gegevens en een naam. Uiteraard moeten de leden hier dan wel toestemming voor geven.

**Comment by Riscky** [comment]
Ik denk dat er op het moment geen behoefte aan is, maar misschien dat anderen daar anders over denken?
