### ISSUE TITLE
Purge flatify from the repo, or recreate the whole thing

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#512]
This is something discussed here: #181.
Flatify.css is not open source, so it should not exist in the history.
This could be achieved by purging flatify.css from the repo, or recreating the repo.
Both are not easy to do while active development is going on, and should be delayed to the summer holidays.
Please make backups ;)

**Comment by Riscky** [comment]
Discussed in the IT Crowd session. We won't do this

**Comment by SilasPeters** [comment]
Is this perhaps worth reopening, @Riscky ?

**Comment by Riscky** [comment]
why?
purging something from version history is hard, and the legal risk of not doing it is debatable but definitely very low.
