### ISSUE TITLE
Add option to navigate to activities index when visiting passed activity

### ISSUE THREAD

**Issue by emielvanrijn** [svsticky/constipated-koala#514]
### Expected behaviour
When navigating to an activity which has passed (e.g. through a mailing received), one should be able to at least navigate back to the activity-index. 

### Actual behavior
Now only "Deze activiteit is (niet) meer beschikbaar. Ga terug." is shown on the page, but there is no 'ga terug' as it was a direct link.

### Steps to reproduce
- Go to an activity which has passed.

**Comment by Mstiekema** [comment]
Duplicate issue #445
