### ISSUE TITLE
Redirect after personal info download

### ISSUE THREAD

**Issue by maartenberg** [svsticky/constipated-koala#567]
The member edit page can get 'stuck' on Firefox if the user downloads their personal information, as the url changes to https://leden.svsticky.nl/download and this breaks the Javascript somehow.
This is probably fixable by either opening the download in a new tab or redirecting the user back to the edit page after the download.

**Comment by Riscky** [comment]
Most sites open downloads in a new tab, I think that is the preferred solution here

**Comment by maartenberg** [comment]
Found something even better, we should be able to set the `download` property on the link: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download
