### ISSUE TITLE
Details panel of Products admin page is not scrollable

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#576]
### Expected behaviour
When product details do not fit in window the details panel becomes scrollable

### Actual behavior
the area is not scrollable, rendering some information invisible

### Steps to reproduce
- admin

**Comment by Mstiekema** [comment]
Not sure how to reproduce this, could you give an example @Riscky ?

**Comment by Riscky** [comment]
![image](https://user-images.githubusercontent.com/15868836/80811741-d7e33a80-8bc6-11ea-93f2-437ee1920844.png)
