### ISSUE TITLE
Mailchimp webhooks throws interest names instead of id's

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#581]
This means we have to keep interest names in sync with mailchimp
OR
just invalidate the cache for the user and ignore the rest of the webhook (best option imho)

**Comment by fiinnnn** [comment]
Example:
```json
"merges": {
	"EMAIL": "froeuw@svsticky.nl",
	"FIRSTNAME": "Mail",
	"LASTNAME": "Chimp",
	"INTERESTS": "ALV, BUSINESS"
}
```
