### ISSUE TITLE
Switch to gettext for our translations

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#616]
see:

https://github.com/ruby-gettext/gettext
https://guides.rubyonrails.org/i18n.html#using-different-backends

This would make translating easier since it works together with more translation tools

**Comment by Mstiekema** [comment]
Cleaned up the translations and added a proper tool for checking translations in #638 For adding translations, just add it to the corresponding yml file. You can also use any of the i18n yml editors, since they will no longer error
