### ISSUE TITLE
Find a better way to set the language for JS

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/constipated-koala#677]
At the moment, the language of the JS is set when you change it or when logging in. You are redirected to `/l?=LG` and the language is set in the session.

The biggest problem with this, is that it's causing #676 and the session ends after a while. There should be a more robust implementation for switching the language.

**Comment by Riscky** [comment]
We set the session language already, so I don't think the redirect is necessary
I removed the redirect for now

**Comment by Mstiekema** [comment]
Where do we set it now? Because the language.js sets it based on the redirect
