### ISSUE TITLE
Bring back Google Calendar sync, this time using the API

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#697]
see https://developers.google.com/calendar/v3/reference/events

**Comment by SilasPeters** [comment]
Is this per activity, or for all activities? We already have per-activity linking through ICS files, but those don't 'sync' with your calendar. If something changes, your calendar won't know, but the user might expect so.

In short, I am highly in favour of per-user syncs. However, then #1037 would be a duplicate. What would be the best way to sync a single person's calendar with a single activity?

**Comment by Riscky** [comment]
#1037 is definitely a duplicate of this, let's close this one.
This was mostly an idea I was toying with at the time, and I didn't really think it through completely.
