### ISSUE TITLE
User still receives emails from old account when having switched

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/constipated-koala#700]
### Expected behaviour
When changing my email from a@mail.com to b@mail.com in Koala, I will only receive emails at b@mail.com 

### Actual behavior
Currently, you will receive emails on both a@email.com & b@email.com

**Comment by fiinnnn** [comment]
While #784 ensures email changes are sent to mailchimp I still have no idea why this happens.

**Comment by Mstiekema** [comment]
As far as I know, that PR fixed this issue, so I'm closing it for now.
