### ISSUE TITLE
Replace Fuzzily by Postgres full text search

### ISSUE THREAD

**Issue by JustNireon** [svsticky/constipated-koala#701]
We are currently using a custom fuzzily for searching members. This system is getting pretty outdated and while testing with this I eceived this deprecation warning
```DEPRECATION WARNING: ActiveSupport::Multibyte::Chars#normalize is deprecated and will be removed from Rails 6.1. Use #unicode_normalize(:nfkd) instead. (called from normalize at /home/nireon/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/bundler/gems/fuzzily-9deddd48a798/lib/fuzzily/trigram.rb:23)```
I'm sure this can get updated but I feel like it's maybe worth looking into a way of changing this search system altogether. A suggestion might be something like this gem https://github.com/mrkamel/search_cop or some other search engine

**Comment by JustNireon** [comment]
https://github.com/Casecommons/pg_search

**Comment by JustNireon** [comment]
https://github.com/sunspot/sunspot Maybe even better

**Comment by Riscky** [comment]
Closed by #844
