### ISSUE TITLE
Mailchimp error on member edit (staging server)

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#716]
![image](https://user-images.githubusercontent.com/15868836/84933385-1c268d80-b0d6-11ea-9b58-5af8b4ad8b4e.png)

**Comment by fiinnnn** [comment]
Should already be fixed, in the current version of koala the lines from the error message look like this:
```ruby
MailchimpJob.perform_later email, @member, params[:member][:mailchimp_interests].reject(&:blank?) unless
  ENV['MAILCHIMP_DATACENTER'].blank? || params[:member][:mailchimp_interests].nil?
```
So reject will never be called on nil.
