### ISSUE TITLE
Translation missing on settings page

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#745]
### Expected behaviour
'Je account is bevestigd, je kunt nu inloggen' or the English equivalent

### Actual behavior
The following message appears:
![image](https://user-images.githubusercontent.com/15868836/93661781-d07bdb00-fa5a-11ea-9cd3-1392e9a66c01.png)

### Steps to reproduce
- Change mailadress in user preferences and save
- Confirm change via email link
- Go to preferences

**Comment by JuannFerrari** [comment]
Hello, 

I could fix this, please assign me the issue. Thanks!
