### ISSUE TITLE
Error when altering email preferences

### ISSUE THREAD

**Issue by essoplerck** [svsticky/constipated-koala#773]
### Expected behaviour
No errors when altering email preferences.

### Actual behavior
I receive a 500 error.

### Steps to reproduce
- user:
Navigate to https://koala.svsticky.nl/edit and press on "Opslaan". This will yield a 500 server error.

- browser:
Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by Riscky** [comment]
Probably the same bug as #768 
Might be due to the user not being in Mailchimp yet?
