### ISSUE TITLE
Email address isn't updated in mailchimp

### ISSUE THREAD

**Issue by fiinnnn** [svsticky/constipated-koala#779]
### Expected behaviour
When a user changes their email in koala the email should be updated in mailchimp as well

### Actual behavior
In mailchimp the address is never changed, so afterwards it seems like the user doesn't exist in mailchimp.
This means they can no longer change their mailing preferences.

Related to #715 and #700

**Comment by Mstiekema** [comment]
Kinda related to this issue, but whenever I click the confirmation link, I get the following error: 
![image](https://user-images.githubusercontent.com/16525696/101360390-e05acc80-389d-11eb-89b2-a3de9334f6b1.png)

**Comment by Riscky** [comment]
See https://mailchimp.com/developer/api/marketing/list-members/add-or-update-list-member/
Basically you need to hash the (old) emailadress of the member to set the new one.
It's not too hard actually, catch is that you want to trigger the change when a users confirms the new mailadres (or am I wrong here?)

**Comment by fiinnnn** [comment]
> Kinda related to this issue, but whenever I click the confirmation link, I get the following error:

Seems there is a typo in `uncofirmed_email`.

While looking into this I also found that when `params['confirmation_token]` is nil, `User.find_by_confirmation_token` will return a user that hasn't changed their email (because the confirmation_token field is NULL for that user).
