### ISSUE TITLE
"Member has payed button" stops updating after one click

### ISSUE THREAD

**Issue by theHam97** [svsticky/constipated-koala#828]
### Expected behaviour
Normally, this button should be able to be used as many times as needed, toggling between payed and not-payed. This system should update the appearance of the button and update the payment status of the member

### Actual behavior
This however does not happen. The button behaves as regular after one click, then when clicked again does not change the state of both the button nor the payment status

### Steps to reproduce
Go to any activity on on the dev account, choose any member and update their payment status by clicking the button next to their name. As you will see, after clicking the button a second time, the status is not updated. This can be fixed by reloading the page, afterwards it will again allow you to update the status once

**Comment by Riscky** [comment]
This has been fixed for some time now
