### ISSUE TITLE
Topping up with a very large number results in a 500 status

### ISSUE THREAD

**Issue by Daruso** [svsticky/constipated-koala#832]
### Expected behaviour
When entering numbers > 9999 into the top up field, the system should reject the attempt.

### Actual behavior
I get directed to the 500 status page (/mongoose), but no transaction is started.

### Steps to reproduce
- user side
- browser: Firefox 89 (but probably reproducable on all modern browsers)

Enter a value over 9999 in the "Tegoed" field on the /member/payments page.

**Comment by Riscky** [comment]
As discussed in the duplicate issue above:

We get status code 422 from Mollie, which we don't catch correctly.
When Mollie throws error codes, we should catch those and display a more useful error message

**Comment by TobiasDeBruijn** [comment]
No longer relevant
