### ISSUE TITLE
Logo doesn't show on login page

### ISSUE THREAD

**Issue by theHam97** [svsticky/constipated-koala#889]
### Expected behaviour
On the login page on chrome, it is expected that the logo shows

### Actual behavior
The logo doesn't show. The image can't be loaded. This only happens on Google Chrome Version 94.0.4606.81 (Official Build) (64-bit) on Ubuntu 20.04. Other browser are unaffected.
![image](https://user-images.githubusercontent.com/19975224/136772059-77960766-56d6-40e5-9382-4f1f0c9a5fce.png)

**Comment by J00LZZ** [comment]
Oh it's already fixed in dev
