### ISSUE TITLE
Feature: allow revoking linked RFID cards by user

### ISSUE THREAD

**Issue by SJ-Zar** [svsticky/constipated-koala#896]
### Expected behaviour
The user can revoke their linked RFID card that was used with the Mongoose. Also un-activated RFID cards should be revokable on the user's page.  This functionality allows the user to have more control over their authorized access cards for use with the Mongoose.

### Actual behavior
Currently only administrators/board members can revoke linked RFID cards.

**Comment by Riscky** [comment]
Since we are building a brand new backend for Mongoose (https://github.com/svsticky/undead-mongoose), I suspect that we should move this issue over there

**Comment by Raymonzut** [comment]
Moved issue got closed
