### ISSUE TITLE
Remove the 'onthoud mij' button 

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#899]
This button is not really functional, and is not used anyway

**Comment by CrookedGrandma** [comment]
@Riscky I've removed the checkbox and the corresponding translations in #922, but is that all? There are other places where the term "remember" is used, but I'm not sure which can be safely deleted, as I'm still a bit new :)
Mainly, in app/models/user.rb there is a `remember_me?` function and I don't _think_ it's used anywhere but I'm not sure.

**Comment by Riscky** [comment]
> Mainly, in app/models/user.rb there is a remember_me? function and I don't think it's used anywhere but I'm not sure.

The `remember_me?` function should be safe to remove.

I have recently talked to someone that was certain that the 'remember me' button was still functional, so we should verify that I guess. This should be as simple as checking the date on the cookie (in the database)

**Comment by Riscky** [comment]
> This should be as simple as checking the date on the cookie (in the database)

Well it is not, there is nothing stored at the server side apparently: https://guides.rubyonrails.org/security.html#session-storage
The expiry date is instead stored clientside, which is not exactly great.
At least I have verified that the 'remember me' functionality is still working, so we might want to discuss if we really want to remove it.

**Comment by Riscky** [comment]
@Jelte-Akker can you chime in? I think you should take this decision.

**Comment by Raymonzut** [comment]
@Riscky I just asked @Jelte-Akker irl, it should be removed
