### ISSUE TITLE
Changing year in activities dropdown filter does not change in dropdown

### ISSUE THREAD

**Issue by Plopmenz** [svsticky/constipated-koala#956]
### Expected behaviour
The dropdown shows the year of the activities listed

### Actual behavior
The dropdown always shows the current year

### Steps to reproduce
- user
- browser:
Change the year on the dashboard / main page for activities listed to 2020-2021
The page will redirect with a url parameter year=2020
The 2020-2021 activities will be listed but the dropdown will show (2021-2022)
This means that the activities list cannot be switch back to 2021-2022 except by changing pages / removing the url paramterer

(Note: only tested on second years, that only have 2 years to choose from in the dropdown, accounts with more years might have different behavior?)
Credits to Lukas Vaartjes for finding this bug

**Comment by Riscky** [comment]
Closing because this is a duplicate of #833
