### ISSUE TITLE
Automated emails reverting to standard concepts

### ISSUE THREAD

**Issue by GitBreax** [svsticky/constipated-koala#976]
### Expected behaviour
Sending a mail to participants of an activity. 

### Actual behavior
It throws out the standard payment email instead of the writen one. 

### Steps to reproduce
- admin/user
Log in as admin, go to activity, write email, press 'verstuur'
- browser:
https://koala.svsticky.nl/activities/####

**Comment by Riscky** [comment]
This should be fixed with #977
