### ISSUE TITLE
Adding a new user results in 500 error

### ISSUE THREAD

**Issue by Mstiekema** [svsticky/constipated-koala#978]
When you try to add a user on your own from the admin UI, you receive a 500. 

![image](https://user-images.githubusercontent.com/16525696/164258993-9aa7653a-6480-4f5c-aee7-0b8b17a92833.png)

**Comment by Raymonzut** [comment]
Reproducability:

- Yes on staging
- No on a clean-checkout without envs
- Yes on a clean-checkout with mailchimp envs set to non-sense
