### ISSUE TITLE
intro.svsticky.nl: Display price including the Ideal costs

### ISSUE THREAD

**Issue by Riscky** [svsticky/constipated-koala#987]
Potential members should be shown the actual price of 7.50 instead of 7.15

**Comment by Raymonzut** [comment]
It already shows 7.50 for master at 0adda652360c9554a7e4ea46c559c793bba59889

Leaving it open as it could be improved to `7.50 (7.15 + 0.35 iDeal)` just like koala activity payments

**Comment by Riscky** [comment]
On production (https://intro.svsticky.nl/), it shows as €7.15
When redirected to Mollie this increases to €7.50 because of the transaction costs.
It would be better to display this directly.
On staging it displays €7.50, but when redirected to Mollie it shows €7.79 (the default setting of transaction costs is €0.29 instead of €0.35).
The transactions costs just don't matter to introduction payments, so it should display €7.50 both on the intro site and when redirected to Mollie, no matter the transaction cost setting.

**Comment by TobiasDeBruijn** [comment]
Fixed with the updating of the intro site in some PRs ago
